
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-15
owner: ucsb-cs156-f24
repo_name: team02-f24-15
pull_requests: [{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-edit-page-actual","number":100,"title":"Added Articles Edit Page, tests, and stories ","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/100"},{"author":{"id":"U_kgDOBkByCg","is_bot":false,"login":"Nopesy","name":"Cooper Hawley"},"headRefName":"coop-page","number":98,"title":"Page initalization","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/98"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-edit-page","number":92,"title":"Added Articles Index Page, tests, and stories","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/92"}]
