
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-15
owner: ucsb-cs156-f24
repo_name: team02-f24-15
pull_requests: [{"author":{"id":"U_kgDOBnFNow","is_bot":false,"login":"sophiaray2101","name":""},"headRefName":"sophiaray2101-recrequest","number":66,"title":"copied files from team01 to team02","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/66"},{"author":{"id":"MDQ6VXNlcjY3MjQ3MzM0","is_bot":false,"login":"riasinha","name":""},"headRefName":"Ria-UCSBOrganization-create-fixtures","number":65,"title":"Completed fixtures for UCSBOrganization","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/65"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-create-fixtures","number":63,"title":"Added fixtures for Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/63"}]
