
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-15
owner: ucsb-cs156-f24
repo_name: team02-f24-15
pull_requests: [{"author":{"id":"U_kgDOBkByCg","is_bot":false,"login":"Nopesy","name":"Cooper Hawley"},"headRefName":"coop-page-edit","number":103,"title":"Page edit + tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/103"}]
