
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-15
owner: ucsb-cs156-f24
repo_name: team02-f24-15
pull_requests: [{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-table-component","number":85,"title":"Added Articles Table Component and Tests, Utils and Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/85"},{"author":{"id":"MDQ6VXNlcjY0MzQwNDE3","is_bot":false,"login":"ranjanbhavya","name":""},"headRefName":"Bhavya-MenuItemReview-fixtures","number":84,"title":"added table components + tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/84"},{"author":{"id":"MDQ6VXNlcjY3MjQ3MzM0","is_bot":false,"login":"riasinha","name":""},"headRefName":"Ria-UCSBOrganization-form-component","number":82,"title":"pushing table component code for review","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/82"},{"author":{"id":"MDQ6VXNlcjU0NDg5MTI4","is_bot":false,"login":"HiDropsy","name":""},"headRefName":"hidropsy-02","number":81,"title":"Closes #46 #47 #48 #49 #50 #51","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/81"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-form-component","number":80,"title":"Added Articles Form Component and Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/80"},{"author":{"id":"U_kgDOBnFNow","is_bot":false,"login":"sophiaray2101","name":""},"headRefName":"sophiaray2101-recrequest","number":79,"title":"finished recommendation request form, test, ansd storybook (maybe)","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/79"},{"author":{"id":"MDQ6VXNlcjU0NDg5MTI4","is_bot":false,"login":"HiDropsy","name":""},"headRefName":"hidropsy-01","number":78,"title":"#46 done","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/78"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-create-fixtures","number":63,"title":"Added fixtures for Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/63"}]
