
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-15
owner: ucsb-cs156-f24
repo_name: team02-f24-15
pull_requests: [{"author":{"id":"U_kgDOBnFNow","is_bot":false,"login":"sophiaray2101","name":""},"headRefName":"sophiaray2101-recrequest","number":79,"title":"finished recommendation request form, test, ansd storybook (maybe)","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/79"},{"author":{"id":"MDQ6VXNlcjU0NDg5MTI4","is_bot":false,"login":"HiDropsy","name":""},"headRefName":"hidropsy-01","number":78,"title":"#46 done","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/78"},{"author":{"id":"U_kgDOBkByCg","is_bot":false,"login":"Nopesy","name":"Cooper Hawley"},"headRefName":"coop","number":75,"title":"Added Fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/75"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-create-fixtures","number":63,"title":"Added fixtures for Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-15/pull/63"}]
